### ISSUE TITLE
can't apply this __setattr__ to instance object

### ISSUE THREAD

**Issue by shinigamiyadav** [gsurma/atari#9]
@gsurma when i run it without rendering it run's fine but when i enable rendering it gives me this error

Traceback (most recent call last):
  File "atari.py", line 100, in <module>
    Atari()
  File "atari.py", line 20, in __init__
    self._main_loop(self._game_model(game_mode, game_name, env.action_space.n), env, render, total_step_limit, total_run_limit, clip)
  File "atari.py", line 45, in _main_loop
    env.render()
  File "/home/overthinker/.local/lib/python2.7/site-packages/gym/core.py", line 235, in render
    return self.env.render(mode, **kwargs)
  File "/home/overthinker/.local/lib/python2.7/site-packages/gym/core.py", line 235, in render
    return self.env.render(mode, **kwargs)
  File "/home/overthinker/.local/lib/python2.7/site-packages/gym/core.py", line 235, in render
    return self.env.render(mode, **kwargs)
  File "/home/overthinker/.local/lib/python2.7/site-packages/gym/core.py", line 235, in render
    return self.env.render(mode, **kwargs)
  File "/home/overthinker/.local/lib/python2.7/site-packages/gym/core.py", line 235, in render
    return self.env.render(mode, **kwargs)
  File "/home/overthinker/.local/lib/python2.7/site-packages/gym/core.py", line 235, in render
    return self.env.render(mode, **kwargs)
  File "/home/overthinker/.local/lib/python2.7/site-packages/gym/envs/atari/atari_env.py", line 152, in render
    from gym.envs.classic_control import rendering
  File "/home/overthinker/.local/lib/python2.7/site-packages/gym/envs/classic_control/rendering.py", line 27, in <module>
    from pyglet.gl import *
  File "/home/overthinker/.local/lib/python2.7/site-packages/pyglet/gl/__init__.py", line 95, in <module>
    from pyglet.gl.lib import GLException
  File "/home/overthinker/.local/lib/python2.7/site-packages/pyglet/gl/lib.py", line 149, in <module>
    from pyglet.gl.lib_glx import link_GL, link_GLU, link_GLX
  File "/home/overthinker/.local/lib/python2.7/site-packages/pyglet/gl/lib_glx.py", line 38, in <module>
    import pyglet.lib
  File "/home/overthinker/.local/lib/python2.7/site-packages/pyglet/lib.py", line 55, in <module>
    script_path = pyglet.resource.get_script_home()
  File "/home/overthinker/.local/lib/python2.7/site-packages/pyglet/__init__.py", line 337, in __getattr__
    object.__setattr__(self, '_module', module)
TypeError: can't apply this __setattr__ to instance object

**Comment by phantom-balance** [comment]
I had the same issue while using gym while using python version 2.7, I just upgraded to python 3.5 in my virtual environment and it seems to fix the issue. Here is a link that might be helpful if you want to know more about it [Link](https://its201.com/article/weixin_44405644/114607171).
